name: app_monitoring
description: App monitoring package with performance tracking widgets
version: 0.0.2
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.0
  overlay_support: ^2.1.0
  leak_tracker: ^11.0.2
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
